# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCG', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
