# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCG', '0002_dish_dishfavourited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishCoverImage',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
