# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCG', '0003_dish_dishcoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishCoverImage',
            field=models.FileField(upload_to=''),
        ),
    ]
