# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCG', '0004_auto_20170515_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishCategory',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink')], default='food', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishRating',
            field=models.IntegerField(default=0),
        ),
    ]
