# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCG', '0006_auto_20170515_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishPublisher',
            field=models.CharField(max_length=250),
        ),
    ]
